RAML 1.0 support
mulesoft-labs/osprey-mock-service pull request #24
Opened 2016-09-23 17:22 UTC by JanMesaric

Added Raml 1.0 support and some basic examples.

2016-09-29 18:33 UTC, jstoiko requested changes

2016-09-29 18:33 UTC, jstoiko commented on examples/api.raml
> +      responses:
extra indent

2016-09-29 18:33 UTC, jstoiko commented on test/osprey-mock-service.js
> +          expect(JSON.parse(res.body)).to.have.any.keys('success')
maybe use `to.deep.equal` here to be more strict

2016-09-29 18:33 UTC, jstoiko commented on test/osprey-mock-service.js
> +          expect(res.body).to.equal('')
`.to.be.empty`

2016-09-29 18:36 UTC, jstoiko commented on test/osprey-mock-service.js
> +          expect(JSON.parse(res.body)).to.have.any.keys('success')
why not `expect(res.body)` shouldn't `res.body` be parsed at this point

2016-09-29 18:56 UTC, jstoiko approved these changes

2016-09-29 19:13 UTC, jstoiko requested changes
also add tests for headers

2016-09-29 19:13 UTC, jstoiko commented on package.json
> +    "popsicle-server": "^2.0.0",
move those 2 to `devDependencies`

2016-10-03 21:24 UTC, JanMesaric commented on package.json
> +    "popsicle-server": "^2.0.0",
done

2016-10-03 21:42 UTC, jstoiko approved these changes

2016-10-04 05:08 UTC, jstoiko requested changes

2016-10-04 05:08 UTC, jstoiko commented on test/fixtures/example10.raml
> +      201:
GET vs 201 status code = not the most "RESTful" example. https://tools.ietf.org/html/rfc7231#section-6.3.2

I would change that response status code to 200.

2016-10-04 05:08 UTC, jstoiko commented on test/test10.js
> +        expect(JSON.parse(res.body)[0].name).to.deep.equal('success')
shouldn't this deep equal `{ "success": { "name": "Working" } }`?

2016-10-04 05:08 UTC, jstoiko commented on test/test10.js
> +        expect(res.status).to.equal(201)
200 here

2016-10-09 08:34 UTC, jstoiko approved these changes

2016-10-09 08:37 UTC, jstoiko commented on examples/index.js
> +parser.loadFile(path.join(__dirname, '/api.raml'))
this doesn't work

2016-10-10 06:16 UTC, jstoiko requested changes
example needs to be fixed

2016-10-12 19:33 UTC, jstoiko approved these changes

2016-11-03 20:21 UTC, llattes reviewed
Just two comments to consider.

2016-11-03 20:21 UTC, llattes commented on package.json
>    },
I think the version of this service should be bumped, not sure if it is a good idea to maintain as `"0.1.0"` with all these changes.

2016-11-03 20:21 UTC, llattes commented on package.json
> +    "osprey": "mulesoft/osprey#raml1.0",
Once the new version is released, remind to change this reference to the corresponding version (0.4.0 I guess from https://github.com/mulesoft/osprey/pull/116/files)

2016-12-13 13:39 UTC, W1R3D-Code commented
Can this be merged in and released yet? Even if its as a pre-release? would make it easier to install :octocat:

2016-12-13 15:58 UTC, rickydutton commented
+1

2016-12-13 17:56 UTC, jstoiko commented
Sorry for the wait. I'd also like this to be merged & released but we're waiting for [an issue ](https://github.com/raml-org/raml-js-parser-2/issues/560) to be fixed in the parser upstream before releasing.

In the meantime, you can install with `npm install git+https://github.com/mulesoft-labs/osprey-mock-service.git#raml1.0`

2017-03-01 01:28 UTC, merged