Fix for issue #30
mulesoft-labs/osprey-mock-service pull request #34
Opened 2017-08-14 16:26 UTC by sichvoge

This PR introduces a fix for #30 and reflects also PR #32. It adds additional tests and takes `example` and `examples` into account. For the latter, it randomly chooses one.

2017-08-14 16:29 UTC, sichvoge commented
@jstoiko before the question comes up - the mocking service does not handle request headers at all. Hence, you don't see it anymore.

Before, those were only copied to the response headers if there isn't any response header defined. That shouldn't be the expected behaviour.

2017-08-16 00:21 UTC, jstoiko requested changes

2017-08-16 00:21 UTC, jstoiko commented on osprey-mock-service.js
> +  if (Array.isArray(response.headers)) {
If we decide to do anything with `method.headers` later on, we may need this. For now though, I would remove that check since we expect the parser to always return `response.headers` as an array. 

This also means that if ever the parser returns anything else, it would throw an error here instead of failing silently (by "failing silently", I mean "not mocking those headers").

2017-08-16 00:21 UTC, jstoiko commented on osprey-mock-service.js
> +        headers[header.name] = header.default || example
`getExampleValueFromHeader()` above gets executed here even when `header.default` is set so I would simply and write `headers[header.name] = header.default || getExampleValueFromHeader(header)` instead.

2017-08-16 00:21 UTC, jstoiko commented on osprey-mock-service.js
> +        headers[header.name] = header.default || example
I would simplify this a bit while making it more explicit (and get rid of `getExampleValueFromHeader()`).
```
if (header.default) {
  headers[header.name] = header.default
} else if (header.example) {
  headers[header.name] = header.example
} else if (header.examples) {
  var randomIndex = Math.floor(Math.random() * header.examples.length)
  headers[header.name] = header.examples[randomIndex].value
}
```
we can also switch the last and second to last statements if `examples` is supposed to supersede `example`.

2017-08-16 05:51 UTC, sichvoge commented on osprey-mock-service.js
> +        headers[header.name] = header.default || example
No, this should be reusable since it will be used to also get a random example from bodies. It's the same logic. We discussed that before.

2017-08-16 06:26 UTC, sichvoge commented
@jstoiko made some changes based on your feedback. Not really sure if nested `if` statements are really needed here, but I don't know too much about best practices in JS to argue against it :)

Other points:
* I left an `if` statement to check if there is a `response.header` defined before going in and iterate through it. Tests were actually failing without any check.
* I want to keep the function `getRandomExampleFromObject` as it will be used for body examples as well. don't want to repeat code.

2017-08-16 21:56 UTC, jstoiko commented
yeah, the extra `if (header)` doesn't look right. It shouldn't be required since `header` is what we're iterating over... unless something is wrong with the output of `response.headers` and it has an empty key. That's all I can think of. I would try again and remove it, if it fails, log `header` and try to figure what happens.

RE the `getRandomExampleFromObject` function that we want to reuse, fair enough. However, I would either rename it (e.g. `getOneExample`) or get the `header.example` (singular form) out of there because if `header.example` is defined, there's nothing "random" about what `getRandomExampleFromObject` returns.

2017-08-17 05:36 UTC, sichvoge commented
Changed the name!

Regarding the `if` statement. I will not remove it since it is the actual check if a header has been defined in RAML or not. If there isn't any header defined, there is no need to process the code block under the `if` statement. 

If there is no header defined `response.headers` will return `undefined` which will obviously fail when you try to call `forEach` on it.

2017-08-17 05:54 UTC, sichvoge commented
OK - after some clarification, the actual `if` statement in question was `if(header)` which is indeed unnecessary. Thanks for clarifying this Jonathan. Removed it.

2017-08-18 16:48 UTC, jstoiko approved these changes

2017-08-18 18:51 UTC, merged